/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**Cria a classe JVerificaVenc
 *
 * @author Claudio Pedra
 */
public class JVerificaVenc extends javax.swing.JFrame {

    /**Este método cria o formulário JVerificaVenc
     * 
     *     * 
     *
     */
    public JVerificaVenc() {
        initComponents();
    }

    JVerificaVenc(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVenc = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonVerifVencido = new javax.swing.JButton();
        jButtonNotifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableVenc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idClientes", "Nome", "Cidade", "Produto", "EmailCliente", "Telefonecliente", "UltimaCompra"
            }
        ));
        jScrollPane1.setViewportView(jTableVenc);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 71, 107));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTROLE TROCA REFIL");

        jLabel15.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(35, 71, 107));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("VERIFICAR VENCIMENTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(124, 124, 124)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(48, 69, 113));
        jLabel3.setText("by PURIFIC Farroupilha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
        );

        jButtonVerifVencido.setText("Verificar vencidos");
        jButtonVerifVencido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifVencidoActionPerformed(evt);
            }
        });

        jButtonNotifica.setText("Notificar...");
        jButtonNotifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jButtonVerifVencido, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNotifica, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNotifica, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButtonVerifVencido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**Faz a conexão com o banco de dados e executa o cálculo para verificar a data do vencimento
     * 
     * @param evt 
     */
    private void jButtonVerifVencidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifVencidoActionPerformed

        try {

            Connection con = jdbc.ConectaBD.getConnection();

            System.out.println("Conectado ao BD");

            String query;

            PreparedStatement stmt;

            query = "SELECT idCLIENTES,Nome,Cidade,Produto,EmailCliente,TelefoneCliente,UltimaCompra, DATEDIFF(CURDATE(), UltimaCompra) AS quantidade_dias FROM clientes WHERE DATEDIFF(CURDATE(), UltimaCompra) > 180";
            stmt = con.prepareStatement(query);

            ResultSet rs;
            rs = stmt.executeQuery();
            DefaultTableModel model;
            model = (DefaultTableModel) jTableVenc.getModel();
            model.setNumRows(0);

            while (rs.next()) {
                model.addRow(
                        new Object[]{
                            rs.getString("idClientes"),
                            rs.getString("Nome"),
                            rs.getString("Cidade"),
                            rs.getString("Produto"),
                            rs.getString("EmailCliente"),
                            rs.getString("TelefoneCliente"),
                            rs.getString("UltimaCompra")
                        }
                );

            }
        } catch (SQLException ex) {
            System.out.println("Ocorreu um erro de SQL !" + ex.getMessage());

        }


    }//GEN-LAST:event_jButtonVerifVencidoActionPerformed

    /**Cria o botão notificar para os registros que atendem o critério de verificação do vencimento
     * 
     * @param evt 
     */
    private void jButtonNotificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotificaActionPerformed

        TableModel vencmodel = jTableVenc.getModel();

        Integer IdClientes = Integer.parseInt(obj3str(vencmodel.getValueAt(jTableVenc.getSelectedRow(), 0)));

        String Nome = (String) jTableVenc.getModel().getValueAt(jTableVenc.getSelectedRow(), 1);
        String Cidade = (String) jTableVenc.getModel().getValueAt(jTableVenc.getSelectedRow(), 2);
        String Produto = (String) jTableVenc.getModel().getValueAt(jTableVenc.getSelectedRow(), 3);
        String EmailCliente = (String) jTableVenc.getModel().getValueAt(jTableVenc.getSelectedRow(), 4);
        String TelefoneCliente = (String) jTableVenc.getModel().getValueAt(jTableVenc.getSelectedRow(), 5);
        String UltimaCompra = (String) jTableVenc.getModel().getValueAt(jTableVenc.getSelectedRow(), 6);

        NotificaClienteView nc = new NotificaClienteView(null, true, IdClientes, Nome, Cidade, Produto, EmailCliente, TelefoneCliente, UltimaCompra);
        nc.setVisible(true);


    }//GEN-LAST:event_jButtonNotificaActionPerformed
    private String obj3str(Object obj) {
        String tmp;
        if (obj == null) {
            tmp = "";
        } else {
            tmp = obj.toString();
        }
        return tmp;
    }
    

    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //</editor-fold>

    /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNotifica;
    private javax.swing.JButton jButtonVerifVencido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVenc;
    // End of variables declaration//GEN-END:variables
}
