/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import modelo.Email;
import javax.mail.*;
import java.util.*;

/**
 * Cria a classe NotificaClienteView
 *
 * @author Claudio Pedra
 */
public class NotificaClienteView extends javax.swing.JDialog {

    /**
     * Este método cria o formulário NotificaClienteView,
     *
     */
    public NotificaClienteView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.novoform = true;
        email = new Email();

    }

    public NotificaClienteView(java.awt.Frame parent, boolean modal, Integer IdClientes, String Nome, String Cidade, String Produto, String EmailCliente, String TelefoneCliente, String UltimaCompra) {
        super(parent, modal);
        initComponents();

        email = new Email();

        this.txtNotifIDCli.setText(IdClientes.toString());
        this.txNotiftNome.setText(Nome);
        this.txtNotifCidade.setText(Cidade);
        this.txtNotifProduto.setText(Produto);
        this.txtNotifEmail.setText(EmailCliente);
        String[] lista3 = UltimaCompra.split("-");
        String DataUltComp = lista3[2] + "/" + lista3[1] + "/" + lista3[0];
        this.txtNotifUltComp.setText(DataUltComp);
        this.novoform = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNotifCodcli = new javax.swing.JPanel();
        txtNotifIDCli = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanelNotifCabecalho = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelNotifDadosCli = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNotifCidade = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txNotiftNome = new javax.swing.JTextField();
        txtNotifProduto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNotifUltComp = new javax.swing.JTextField();
        jPanelNotificaCli = new javax.swing.JPanel();
        txtNotifEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonEnviaNotifi = new javax.swing.JButton();
        jTxtNotifMsg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelNotifCodcli.setBorder(javax.swing.BorderFactory.createTitledBorder("Código do Cliente"));

        txtNotifIDCli.setEditable(false);

        jLabel13.setText("Id Cliente");

        javax.swing.GroupLayout jPanelNotifCodcliLayout = new javax.swing.GroupLayout(jPanelNotifCodcli);
        jPanelNotifCodcli.setLayout(jPanelNotifCodcliLayout);
        jPanelNotifCodcliLayout.setHorizontalGroup(
            jPanelNotifCodcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNotifCodcliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotifIDCli, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanelNotifCodcliLayout.setVerticalGroup(
            jPanelNotifCodcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotifCodcliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNotifCodcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNotifIDCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNotifCabecalho.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 71, 107));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONTROLE TROCA REFIL");

        jLabel18.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(35, 71, 107));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("NOTIFICAÇÃO DE CLIENTES");

        javax.swing.GroupLayout jPanelNotifCabecalhoLayout = new javax.swing.GroupLayout(jPanelNotifCabecalho);
        jPanelNotifCabecalho.setLayout(jPanelNotifCabecalhoLayout);
        jPanelNotifCabecalhoLayout.setHorizontalGroup(
            jPanelNotifCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotifCabecalhoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addGap(91, 91, 91)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNotifCabecalhoLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 453, Short.MAX_VALUE))
        );
        jPanelNotifCabecalhoLayout.setVerticalGroup(
            jPanelNotifCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotifCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanelNotifCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelNotifDadosCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jLabel14.setText("Nome");

        jLabel21.setText("Cidade");

        txNotiftNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNotiftNomeActionPerformed(evt);
            }
        });

        jLabel22.setText("Produto");

        jLabel23.setText("Última compra");

        javax.swing.GroupLayout jPanelNotifDadosCliLayout = new javax.swing.GroupLayout(jPanelNotifDadosCli);
        jPanelNotifDadosCli.setLayout(jPanelNotifDadosCliLayout);
        jPanelNotifDadosCliLayout.setHorizontalGroup(
            jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotifDadosCliLayout.createSequentialGroup()
                .addGroup(jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNotifDadosCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(jPanelNotifDadosCliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel21))
                    .addGroup(jPanelNotifDadosCliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14))
                    .addGroup(jPanelNotifDadosCliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNotifProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNotiftNome, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotifCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNotifUltComp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNotifDadosCliLayout.setVerticalGroup(
            jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNotifDadosCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txNotiftNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotifCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotifProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelNotifDadosCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtNotifUltComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelNotificaCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Notificação de Cliente"));

        txtNotifEmail.setEditable(false);

        jLabel19.setText("Email");

        jButtonEnviaNotifi.setText("Enviar Notificação");
        jButtonEnviaNotifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviaNotifiActionPerformed(evt);
            }
        });

        jLabel9.setText("Mensagem");

        javax.swing.GroupLayout jPanelNotificaCliLayout = new javax.swing.GroupLayout(jPanelNotificaCli);
        jPanelNotificaCli.setLayout(jPanelNotificaCliLayout);
        jPanelNotificaCliLayout.setHorizontalGroup(
            jPanelNotificaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotificaCliLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelNotificaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNotificaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtNotifMsg)
                    .addComponent(txtNotifEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jButtonEnviaNotifi)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanelNotificaCliLayout.setVerticalGroup(
            jPanelNotificaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotificaCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNotificaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotifEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jButtonEnviaNotifi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNotificaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNotifMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNotifCabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNotifCodcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelNotifDadosCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNotificaCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelNotifCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanelNotifCodcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNotifDadosCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNotificaCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNotiftNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNotiftNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNotiftNomeActionPerformed

    private void jButtonEnviaNotifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviaNotifiActionPerformed
        String msgMail = jTxtNotifMsg.getText();
        String para = txtNotifEmail.getText();
        email.enviarEmail(msgMail, para);

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnviaNotifiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificaClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificaClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificaClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificaClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotificaClienteView dialog = new NotificaClienteView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private Integer IdClientes;
    private boolean novoform;
    private Email email;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviaNotifi;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelNotifCabecalho;
    private javax.swing.JPanel jPanelNotifCodcli;
    private javax.swing.JPanel jPanelNotifDadosCli;
    private javax.swing.JPanel jPanelNotificaCli;
    private javax.swing.JTextField jTxtNotifMsg;
    public javax.swing.JTextField txNotiftNome;
    public javax.swing.JTextField txtNotifCidade;
    public javax.swing.JTextField txtNotifEmail;
    private javax.swing.JTextField txtNotifIDCli;
    public javax.swing.JTextField txtNotifProduto;
    private javax.swing.JTextField txtNotifUltComp;
    // End of variables declaration//GEN-END:variables

    private void enviaEmail() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
